volumes:
  dbdata:
  django_static:

services:
  db:
    image: timescale/timescaledb-ha:pg17-ts2.21@sha256:a2f4731fd341e93a96fdc49f21137db0ec27bd3d72a5dab241fec2b344f2f54c
    ports:
      - "${BUOY_RETRIEVER_DB_PORT:-5432}:5432"
    env_file:
      - ./docker-data/secret.env
    # environment:
    #   PGDATA: /var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker-data/db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-buoy_retriever}"]
      interval: 2s
      timeout: 5s
      retries: 5

  # cache:
  #   image: redis:6.0.7@sha256:0ab24e410ae42f99f1e861bd351b5ce7ca8c9eec7886c979a8650ba7fc18ad3b

  # queue:
  #   image: redis:6.0.7@sha256:0ab24e410ae42f99f1e861bd351b5ce7ca8c9eec7886c979a8650ba7fc18ad3b

  spotlight:
    image: ghcr.io/getsentry/spotlight:latest
    ports:
      - "${BUOY_RETRIEVER_SPOTLIGHT_PORT:-8969}:8969"

  backend:
    build:
      context: ./backend
      target: develop
    image: buoy_retriever_backend
    command: "python manage.py runserver 0:8080"
    # For testing backend when running behind uwsgi
    # command: >
    #   sh -c 'python manage.py collectstatic --noinput
    #   && uwsgi --http 0.0.0.0:8080
    #   --module buoy_retriever.wsgi
    #   --static-map /backend/static=/static --master --log-master
    #   --processes 4 --threads 2
    #   '
    volumes:
      - ./backend:/home/uwsgi/app:cached
      # - ./docker-data/uwsgi-pixi:/home/uwsgi/.pixi
      - ./docker-data/media:/media:cached
      - django_static:/static:rw
    ports:
      - "${BUOY_RETRIEVER_BACKEND_PORT:-8080}:8080"
    env_file:
      - ./docker-data/common.env
      - ./docker-data/secret.env
    environment:
      BACKEND_ENV: dev
      POSTGRES_HOST: db
      # Allows for setting schema to something other than 'public'
      POSTGRES_OPTIONS: "-c search_path=buoy_retriever"
      # CACHE_HOST: cache
      # QUEUE_HOST: queue
      # Allow for setting additional CSRF trusted origins
      # DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:54321"
    depends_on:
      db:
        condition: service_healthy
    # - cache
    # - queue

  frontend:
    image: "strm/helloworld-http:latest"
    ports:
      - 5555:80

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     target: dev
  #   command: npm run dev
  #   stdin_open: true
  #   volumes:
  #     - ./frontend:/app:cached
  #     - ./docker-data/app/node_modules:/app/node_modules
  #     - ./docker-data/app/.next/:/app/.next/
  #     - ./docker-data/app/build/:/app/build/
  #   ports:
  #     - "${BUOY_RETRIEVER_FRONTEND_PORT:-3000}:3000"
  #   environment:
  #     NEXT_PUBLIC_BACKEND_URL: http://backend:8080

  proxy:
    image: "buoy_retriever_proxy:latest"
    build:
      context: ./proxy
      dockerfile: Dockerfile
    # volumes:
    #   - ...
    ports:
      - "9090:9090"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started

  dagster_postgres:
    image: timescale/timescaledb-ha:pg17-ts2.21@sha256:a2f4731fd341e93a96fdc49f21137db0ec27bd3d72a5dab241fec2b344f2f54c
    environment:
      PGDATA: /var/lib/postgresql/data/PGDATA
    env_file:
      - ./docker-data/dagster.env
    volumes:
      - ./docker-data/dagster_postgres:/var/lib/postgresql/data:cached
    ports:
      - "${BUOY_RETRIEVER_DAGSTER_DB_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  dagster_daemon:
    build: ./pipeline/_dagster
    command:
    - dagster-daemon
    - run
    env_file:
    - ./docker-data/dagster.env
    volumes:
      - ./pipeline/_dagster/workspace.yaml:/home/ioos/workspace.yaml
      - ./pipeline/_dagster/dagster.yaml:/home/ioos/dagster.yaml
      - ./docker-data/dagster_home/storage:/home/ioos/storage
    depends_on:
      dagster_postgres:
        condition: service_healthy

  dagster_ui:
    build: ./pipeline/_dagster
    env_file:
    - ./docker-data/dagster.env
    ports:
      - "${BUOY_RETRIEVER_DAGSTER_UI_PORT:-3002}:3002"
    volumes:
      - ./pipeline/_dagster/workspace.yaml:/home/ioos/workspace.yaml
      - ./pipeline/_dagster/dagster.yaml:/home/ioos/dagster.yaml
      - ./docker-data/dagster_home/storage:/home/ioos/storage
    depends_on:
      dagster_postgres:
        condition: service_healthy
      dagster_daemon:
        condition: service_started

  s3_timeseries:
    build:
      context: .
      dockerfile: ./pipeline/s3_timeseries/Dockerfile
      args:
        IMAGE_TAG: s3_timeseries_dev
    env_file:
    - ./docker-data/common.env
    - ./docker-data/dagster.env
    - ./docker-data/secret.env
    - ./docker-data/s3_pipeline.env
    volumes:
      - ./pipeline/s3_timeseries:/home/ioos:cached
      - /home/ioos/.pixi
      - ./common/:/home/ioos/common/:cached
      - ./docker-data/shared-fs:/mnt/efs/
      - ./docker-data/datasets_config/s3_pipeline/metadata/:/mnt/datasets_config/metadata
    depends_on:
      backend:
        condition: service_started

  hohonu:
    build:
      context: .
      dockerfile: ./pipeline/hohonu/Dockerfile
      args:
        IMAGE_TAG: hohonu_dev
    env_file:
    - ./docker-data/common.env
    - ./docker-data/dagster.env
    - ./docker-data/secret.env
    volumes:
      - ./pipeline/hohonu:/home/ioos:cached
      - /home/ioos/.pixi
      - ./common/:/home/ioos/common/:cached
      - ./docker-data/shared-fs:/mnt/efs/
    depends_on:
      backend:
        condition: service_started
